export const competitionsData = [
  {
    competition_id: "69",
    name: "Afghan Premier League",
    teamtype: "male",
    type: "club",
    format: "domestic_league",
    area_id: "8",
    area_name: "Afghanistan",
    last_updated: "2018-07-18 16:29:54",
    isFavorite: true,
  },
  {
    competition_id: "44",
    name: "Africa Cup of Nations",
    teamtype: "male",
    type: "international",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2019-06-21 15:51:02",
  },
  {
    competition_id: "236",
    name: "CAF Champions League",
    teamtype: "male",
    type: "club",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2019-07-31 10:18:32",
  },
  {
    competition_id: "254",
    name: "CAF Confederation Cup",
    teamtype: "male",
    type: "club",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-07-17 14:43:27",
  },
  {
    competition_id: "325",
    name: "AFCON Qualification",
    teamtype: "male",
    type: "international",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-09-08 13:13:12",
  },
  {
    competition_id: "354",
    name: "WC Qualification",
    teamtype: "male",
    type: "international",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-06-07 10:11:21",
  },
  {
    competition_id: "10",
    name: "CAF Super Cup",
    teamtype: "male",
    type: "club",
    format: "international_super_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-06-11 01:03:48",
  },
  {
    competition_id: "255",
    name: "African Nations Championship",
    teamtype: "male",
    type: "international",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-07-17 14:43:48",
  },
  {
    competition_id: "211",
    name: "CECAFA Cup",
    teamtype: "male",
    type: "international",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-07-17 14:43:21",
  },
  {
    competition_id: "660",
    name: "CHAN Qualification",
    teamtype: "male",
    type: "international",
    format: "international_cup",
    area_id: "3",
    area_name: "Africa",
    last_updated: "2018-07-17 14:43:51",
  },
];
